# - debug: var=ansible_system

# - name: ping
#   ping:
#   when: ansible_system != 'Win32NT'

# - name: win_ping
#   action: win_ping
#   when: ansible_system == 'Win32NT'

# - name: Hello, World!
#   action: "{{ filename }}"
#   register: hello_world

# - assert:
#     that:
#       - 'hello_world.msg == "Hello, World!"'

- name: Module CCA Diff
  action: "{{ filename }}"
  args:
    name: cca_diff
    file1: "{{ playbook_dir }}/1.txt"
    file2: "{{ playbook_dir }}/2.txt"
  register: hello_ansible

- name: Debug CCA Diff
  debug:
    var: hello_ansible

# - assert:
#     that:
#       - 'hello_ansible.msg == "Hello, Ansible!"'

# - name: Async Hello, World!
#   action: "{{ filename }}"
#   async: 10
#   poll: 1
#   when: ansible_system != 'Win32NT'
#   register: async_hello_world

# - assert:
#     that:
#       - 'async_hello_world.msg == "Hello, World!"'
#   when: async_hello_world is not skipped

# - name: Async Hello, Ansible!
#   action: "{{ filename }}"
#   args:
#     name: Ansible
#   async: 10
#   poll: 1
#   when: ansible_system != 'Win32NT'
#   register: async_hello_ansible

# - assert:
#     that:
#       - 'async_hello_ansible.msg == "Hello, Ansible!"'
#   when: async_hello_ansible is not skipped
